CoreMyAppAncket/Models/AncketVievModels/Ancket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMyAppAncket.Models.AncketVievModels
{
    public class Ancket
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public bool IsSendMail { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
        
        public virtual List<AncketForm> AncketForms { get; set; }

        

    }
}

CoreMyAppAncket/Models/AncketVievModels/AncketForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMyAppAncket.Models.AncketVievModels
{
    public class AncketForm
    {
        public int Id { get; set; }
        public string FormName { get; set; }
        public FormType FormType { get; set; }
        public bool IsValid { get; set; }
        public long TextBoxIntData { get; set; }
        public string TextBoxStringData { get; set; }
        public bool CheckBoxData { get; set; }

        public int AncketId { get; set; }
        public virtual Ancket Ancket { get; set; }

    }

    public enum FormType
    {
        TextBoxString,
        TextArea,
        TextBoxInt,
        Email,
        Phone,
        CheckBox,
        ComboBox
    }
}

CoreMyAppAncket/Controllers/AncketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreMyAppAncket.Data;
using CoreMyAppAncket.Models.AncketVievModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Identity;
using CoreMyAppAncket.Models;
using Microsoft.AspNetCore.Authorization;
using PagedList.Core;
using PaulMiami.AspNetCore.Mvc.Recaptcha;
using System.Net.Http;
using Microsoft.Extensions.Logging;
using System.Net;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.Configuration;
using CoreMyAppAncket.Services;

namespace CoreMyAppAncket.Controllers
{
    [RequireHttps]
    [Authorize]
    public class AncketController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly ILogger _logger;
        public AncketController(ApplicationDbContext context,
                                UserManager<ApplicationUser> manager,
                                IConfiguration configuration,
                                ILogger<AncketController> logger)
        {
            db = context;
            _userManager = manager;
            _configuration = configuration;
            _logger = logger;
        }
        // GET: Ancket
        [Authorize]
        public ActionResult Index()
        {
            List<Ancket> anckets = new List<Ancket>();
            Dictionary<int, int> results = new Dictionary<int, int>();
            var userId = _userManager.GetUserId(HttpContext.User);
            foreach (var item in db.Anckets.Where(t => t.UserId == userId).ToList())
            {
                Ancket ancket = item;
                ancket.AncketForms = db.AncketForms.Where(t => t.AncketId == item.Id).ToList();
                anckets.Add(ancket);
                results.Add(ancket.Id, db.AncketResults.Where(t => t.AncketId == ancket.Id).Count());

            }

            ViewBag.Results = results;
            return View(anckets);
        }


        // GET: Ancket/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                Ancket ancket = db.Anckets.Find(id);
                ancket.AncketForms = db.AncketForms.Where(x => x.AncketId == id).ToList();

                return View(ancket);
            }
            else
            {

                Ancket ancket = new Ancket()
                {
                    AncketForms = new List<AncketForm>()
                };
                return View(ancket);
            }

        }


        // POST: Ancket/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Ancket ancket, Dictionary<string, AncketForm> ancketForms)
        {
            try
            {
                if (ancket != null)
                {
                    var userId = _userManager.GetUserId(HttpContext.User);
                    Ancket a = new Ancket()
                    {
                        Id = ancket.Id,
                        Name = ancket.Name,
                        Date = DateTime.Now,
                        UserId = userId,
                        IsSendMail=ancket.IsSendMail
                    };
                    a.AncketForms = new List<AncketForm>();
                    foreach (var item in ancketForms)
                    {
                        a.AncketForms.Add(item.Value);
                    }

                    if (ancket.Id != 0)
                    {
                        var forms = db.AncketForms.Where(t => t.AncketId == ancket.Id).ToList();
                        db.AncketForms.RemoveRange(forms);
                        db.Anckets.Update(a);
                    }
                    else
                    {
                        db.Anckets.Add(a);
                    }

                    db.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View(e);
            }
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ancket = await db.Anckets.FindAsync(id);
            if (ancket == null)
            {
                return NotFound();
            }

            return View(ancket);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var a = await db.Anckets.FindAsync(id);
                db.Anckets.Remove(a);
                await db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult ViewAncket(int? id, Ancket ancket, Dictionary<string, AncketForm> ancketForms)
        {
            if (id == null)
            {
                Ancket a = new Ancket()
                {
                    Id = ancket.Id,
                    Name = ancket.Name,
                    Date = DateTime.Now
                };
                a.AncketForms = new List<AncketForm>();
                foreach (var item in ancketForms)
                {
                    a.AncketForms.Add(item.Value);
                }

                return View(a);
            }
            else
            {
                Ancket aa = db.Anckets.Find(id);
                aa.AncketForms = db.AncketForms.Where(t => t.AncketId == id).ToList();
                return View(aa);
            }


        }


        public ActionResult AncketForm()
        {
            AncketForm ancketForm = new AncketForm();
            return View("AncketForm", new KeyValuePair<string, AncketForm>(
                            Guid.NewGuid().ToString("N"),
                            ancketForm));
        }

        public ActionResult FormData(string typeno, string key, AncketForm ancketForm)
        {

            ancketForm.FormType = (FormType)Enum.Parse(typeof(FormType), typeno);

            return View("FormData", new KeyValuePair<string, AncketForm>(key, ancketForm));
        }

        public ActionResult Results(int? id, int? page)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ancket = db.Anckets.Find(id);
            if (ancket == null)
            {
                return NotFound();
            }
            var results = db.AncketResults.Where(t => t.AncketId == id);
            foreach (var item in results)
            {
                item.AncketFormResults = db.AncketFormResults.Where(t => t.AncketResultId == item.Id).ToList();
            }

            int pageSize = 2;
            int pageNumber = page ?? 1;


            ViewBag.Ancket = ancket;
            return View(results.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AncketEnterData(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Ancket ancket = await db.Anckets.FindAsync(id);
            if (ancket == null)
            {
                return NotFound();
            }

            ancket.AncketForms = db.AncketForms.Where(t => t.AncketId == id).ToList();
            ViewData["ReCaptchaKey"] = _configuration.GetSection("Recaptcha:SiteKey").Value;
            return View(ancket);
        }

        //[ValidateRecaptcha]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> AncketEnterDate(Ancket ancket, Dictionary<string, AncketForm> ancketForms)
        {
            
                try
                {

                    AncketResult ancketResult = new AncketResult()
                    {
                        AncketId = ancket.Id,
                        AncketName = ancket.Name,
                        AncketFormResults = new List<AncketFormResult>()
                    };

                

                foreach (var item in ancketForms)
                    {

                        if (item.Value.FormType.Equals(FormType.CheckBox))
                        {
                            ancketResult.AncketFormResults.Add(new AncketFormResult()
                            {
                                FormType = item.Value.FormType,
                                NameForm = item.Value.FormName,
                                CheckBoxData = item.Value.CheckBoxData
                            });
                        }
                        else if (item.Value.FormType.Equals(FormType.ComboBox) || item.Value.FormType.Equals(FormType.TextArea) || item.Value.FormType.Equals(FormType.TextBoxString))
                        {
                            ancketResult.AncketFormResults.Add(new AncketFormResult()
                            {
                                FormType = item.Value.FormType,
                                NameForm = item.Value.FormName,
                                StringData = item.Value.TextBoxStringData
                            });
                        }
                        else if (item.Value.FormType.Equals(FormType.Email))
                        {
                            ancketResult.AncketFormResults.Add(new AncketFormResult()
                            {
                                FormType = item.Value.FormType,
                                NameForm = item.Value.FormName
                            });

CoreMyAppAncket/Views/Ancket/AncketEnterData.cshtml
@using CoreMyAppAncket.Models.AncketVievModels
@using PaulMiami.AspNetCore.Mvc.Recaptcha
@model CoreMyAppAncket.Models.AncketVievModels.Ancket

@{
    ViewData["Title"] = "AncketEnterDate";
}

<h2>@Model.Name</h2>
<hr />


@using (Html.BeginForm("AncketEnterDate", "Ancket", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(m => Model.Name)
    @Html.HiddenFor(m => Model.IsSendMail)
    <div class="divTable paleBlueRows">
        <div class="divTableHeading">
            <div class="divTableRow">
                <div class="divTableHead">NameForm</div>
                <div class="divTableHead">Value</div>
            </div>
        </div>
        <div class="divTableBody" id="divTableBody">

            @{
                foreach (var item in Model.AncketForms)
                {
                    @Html.Hidden("AncketForms[" + item.Id + "].FormType", item.FormType)
                    @Html.Hidden("AncketForms[" + item.Id + "].Id", item.Id)                    
                    <div class="divTableRow">

                        @if (item.FormType.Equals(FormType.CheckBox))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @Html.CheckBox("AncketForms[" + item.Id + "].CheckBoxData", item.CheckBoxData, new { @class = "form-check-input" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.ComboBox))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @{ var st = item.TextBoxStringData.Split(";");}

                                @Html.DropDownList("AncketForms[" + item.Id + "].TextBoxStringData", new SelectList(st.ToList()), new { @class = "form-control", @type = "text" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.Email))
                        {                            
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormType)
                            </div>
                            <div class="divTableCell">
                                @Html.TextBox("AncketForms[" + item.Id + "].FormName", item.FormName, new { @class = "form-control", @type = "text" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.Phone))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @Html.TextBox("AncketForms[" + item.Id + "].TextBoxIntData", item.TextBoxIntData, new { @class = "form-control", @placeholder = "380983332211", @type = "text" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.TextArea))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @Html.TextArea("AncketForms[" + item.Id + "].TextBoxStringData", item.TextBoxStringData, new { @class = "form-control", @type = "text" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.TextBoxInt))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @Html.TextBox("AncketForms[" + item.Id + "].TextBoxIntData", item.TextBoxIntData, new { @class = "form-control", @type = "number" })
                            </div>
                        }
                        else if (item.FormType.Equals(FormType.TextBoxString))
                        {
                            @Html.Hidden("AncketForms[" + item.Id + "].FormName", item.FormName)
                            <div class="divTableCell">
                                @Html.DisplayFor(m => item.FormName)
                            </div>
                            <div class="divTableCell">
                                @Html.TextBox("AncketForms[" + item.Id + "].TextBoxStringData", item.TextBoxStringData, new { @class = "form-control", @type = "text" })
                            </div>
                        }
                    </div>
                }

            }

        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="g-recaptcha" data-sitekey="@ViewData["ReCaptchaKey"]" data-callback="enableBtn"></div>
            </div>
            <div class="col - md - 2">
                <br />
                <input id="savebtn" type="button" class="btn btn-primary btn-lg" method="post" name="action" value="Submit">
            </div>
        </div>
    </div>

}


@section Scripts {
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <link href="~/css/ancket-edit/ancket-edit.css" rel="stylesheet" type="text/css" />
    <script>
        $(document).ready(function () {
            $("#savebtn").on("click", function (e) {
                var recaptcha = $("#g-recaptcha-response").val();
                if (recaptcha === "") {
                    alert("Please check the recaptcha");
                } else {
                    $.ajax({
                        async: false,
                        url: "/Ancket/Verify",
                        method: "GET",
                        data: { "gRecaptchaResponse": recaptcha },

                        success: function (response) {
                            if (response === true) {
                                $("form").submit();
                            } else {
                                alert("captcha verification NOT successful \n" + JSON.stringify(response));
                                e.preventDefault();
                                return false;
                            }
                        },

                        error: function (jqXHR, textStatus, errorThrown) {
                            alert("captcha verification NOT successful");
                            e.preventDefault();
                            return false;
                        }
                    });
                }
            });
        });

    </script>
}

CoreMyAppAncket/Views/Ancket/AncketForm.cshtml
@using CoreMyAppAncket.Models.AncketVievModels
@model KeyValuePair<string, CoreMyAppAncket.Models.AncketVievModels.AncketForm>

@{
    Layout = null;
    var key = Model.Key;
}

<div class="divTableRow" id="FormRow_@key">
    <div class="divTableCell">
        @Html.CheckBox("CheckRow", new { @class = "form-check-input", @id = "CheckRow" })
    </div>
    <div class="divTableCell" id="divTableCell">
        @Html.DropDownList("AncketForms[" + Model.Key + "].FormType",
                                                       new SelectList(Enum.GetValues(typeof(FormType)), Model.Value.FormType), new { @class =  "form-control",  @key = key })
    </div>
    <div class="divTableCell">
        @Html.TextBox("AncketForms[" + Model.Key + "].FormName", Model.Value.FormName, new { @class = "form-control" })
    </div>
    <div class="divTableCell" id="Item_@key">
        @Html.CheckBox("AncketForms[" + Model.Key + "].IsValid", Model.Value.IsValid, new { @class = "form-check-input" })
    </div>
    @Html.Partial("FormData", Model)
</div>

CoreMyAppAncket/Views/Ancket/Create.cshtml
@model CoreMyAppAncket.Models.AncketVievModels.Ancket

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Ancket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CoreMyAppAncket/Views/Ancket/Delete.cshtml
@model CoreMyAppAncket.Models.AncketVievModels.Ancket

@{
    ViewData["Title"] = "Delete";
}

<h2></h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ancket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Ancket Name")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoreMyAppAncket/Views/Ancket/Details.cshtml
@model CoreMyAppAncket.Models.AncketVievModels.Ancket

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ancket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CoreMyAppAncket/Views/Ancket/Edit.cshtml
@using CoreMyAppAncket.Models.AncketVievModels;
@model CoreMyAppAncket.Models.AncketVievModels.Ancket

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<hr />
@using (Html.BeginForm("Edit", "Ancket", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <fieldset>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2"><label>Name Ancket</label></div>
                <div class="col-md-4">
                    @Html.TextBox("Name", Model.Name, new { @class = "form-control" })
                    @Html.ValidationMessage("Name")
                </div>
                <div class="col-md-3">
                    
                    <button asp-action="ViewAncket" asp-controller="Ancket" class="btn btn-primary" asp-route-id="@Model" formtarget="_blank">View</button>                    
                    <button type="submit" class="btn btn-primary" method="post" name="action" value="save">Save</button>                   
                    <button asp-action="Index" asp-controller="Ancket" class="btn btn-primary">Cancel</button>                  
                 </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div type="button" class="btn btn-primary btn-sm" id="AncketForm">Add form</div>
                    <div type="button" class="btn btn-primary btn-sm" id="remove-line">Remove line</div>
                    <div type="button" class="btn btn-success btn-sm" id="upbtn">Up</div>
                    <div type="button" class="btn btn-success btn-sm" id="downbtn">Down</div>
                </div>
            </div>

            <div class="divTable paleBlueRows">
                <div class="divTableHeading">
                    <div class="divTableRow">
                        <div class="divTableHead">InitForm</div>
                        <div class="divTableHead">TypeForm</div>
                        <div class="divTableHead">NameForm</div>
                        <div class="divTableHead">IsValid*</div>
                        <div class="divTableHead">Value</div>
                    </div>
                </div>
                <div class="divTableBody" id="divTableBody">
                    @foreach (var item in Model.AncketForms)
                    {                       
                         @Html.Partial("AncketForm", new KeyValuePair<string, AncketForm>(Guid.NewGuid().ToString("N"), item))                        
                    }
                </div>
            </div>
        </div>
        <div>
            <text>Send form to yor Email?</text>
            @Html.CheckBox("IsSendMail",Model.IsSendMail,new {@class = "form-check-input" })
        </div>
    </fieldset>
}




@section Scripts {
    <script type="text/javascript" src="~/js/ancket-edit/ancket-edit.js"></script>
    <link href="~/css/ancket-edit/ancket-edit.css" rel="stylesheet" type="text/css" />
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMyAppAncket/Views/Ancket/FormData.cshtml
@using CoreMyAppAncket.Models.AncketVievModels
@model KeyValuePair<string, CoreMyAppAncket.Models.AncketVievModels.AncketForm>

@{
    Layout = null;

}

@{
    if (Model.Value.FormType.Equals(FormType.TextBoxString))
    {
        <div class="divTableCell">
            @Html.TextBox("AncketForms[" + Model.Key + "].TextBoxStringData", Model.Value.TextBoxStringData, new { @class = "form-control", type = "text" })
        </div>

    }
    else if (Model.Value.FormType.Equals(FormType.TextBoxInt))
    {
        <div class="divTableCell">
            @Html.TextBox("AncketForms[" + Model.Key + "].TextBoxIntData", Model.Value.TextBoxIntData, new { @class = "form-control", type = "text" })
        </div>
    }
    else if (Model.Value.FormType.Equals(FormType.TextArea))
    {
        <div class="divTableCell">
            @Html.TextArea("AncketForms[" + Model.Key + "].TextBoxStringData", Model.Value.TextBoxStringData, new { @class = "form-control", type = "text", rows = "3" })
        </div>
    }
    else if (Model.Value.FormType.Equals(FormType.Phone))
    {
        <div class="divTableCell">
            @Html.TextBox("AncketForms[" + Model.Key + "].TextBoxIntData", Model.Value.TextBoxIntData, new { @class = "form-control", type = "text", placeholder = "380501112233" })
        </div>
    }
    else if (Model.Value.FormType.Equals(FormType.Email))
    {
        <div class="divTableCell"></div>
        <div class="divTableCell"></div>
    }
    else if (Model.Value.FormType.Equals(FormType.ComboBox))
    {
        <div class="divTableCell">
            @Html.TextBox("AncketForms[" + Model.Key + "].TextBoxStringData", Model.Value.TextBoxStringData, new { @class = "form-control", type = "text" })
        </div>

    }
    else if (Model.Value.FormType.Equals(FormType.CheckBox))
    {
        <div class="divTableCell">
            @Html.CheckBox("AncketForms[" + Model.Key + "].CheckBoxData", Model.Value.CheckBoxData, new { @class = "form-check-input" })
        </div>
    }
}

CoreMyAppAncket/Views/Ancket/Index.cshtml
@model IEnumerable<CoreMyAppAncket.Models.AncketVievModels.Ancket>

@{
    ViewData["Title"] = "Index";
    Dictionary<int, int> r = ViewBag.Results;
}

<br />
<form >
    <button asp-action="Edit" asp-controller="Ancket" asp-route-id="@null" class="btn btn-primary" method="get">Create New</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="ViewAncket" asp-route-id="@item.Id">@item.Name</a>
                        @*@Html.DisplayFor(modelItem => item.Name)*@
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Results" asp-route-id="@item.Id">results - @r.GetValueOrDefault(key: @item.Id) </a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                        @Html.DisplayFor(model=>item.Date,new { @class="from-control"})|
                        @Html.ActionLink("Link to Ancket", "AncketEnterData","Ancket", new { id = @item.Id }, null )
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

CoreMyAppAncket/Views/Ancket/Results.cshtml
@using CoreMyAppAncket.Models.AncketVievModels
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<CoreMyAppAncket.Models.AncketVievModels.AncketResult>

@{
    ViewData["Title"] = "Results";
    Ancket a = ViewBag.Ancket;
    // Dictionary<int, List<AncketFormResult>> res = ViewBag.Results;
}

<h2>@a.Name Results</h2>

<div class="divTable paleBlueRows">
    <div class="divTableHeading">
        <div class="divTableRow">
            <div class="divTableHead">NameForm</div>
            <div class="divTableHead">Value</div>
        </div>
    </div>
    <div class="divTableBody" id="divTableBody">

        @foreach (var item in Model)
        {

            @foreach (var it in item.AncketFormResults)
            {<div class="divTableRow">
                    <div class="divTableCell">
                        @{
                            if (it.FormType.Equals(FormType.Email))
                            {
                                <text>Email</text>
                            }
                            else
                            {
                                @Html.DisplayFor(m => it.NameForm)
                            }
                        }

                    </div>
                    <div class="divTableCell">
                        @{
                            if (it.FormType.Equals(FormType.ComboBox) || it.FormType.Equals(FormType.TextArea) || it.FormType.Equals(FormType.TextBoxString))
                            {
                                @Html.DisplayFor(m => it.StringData)
                            }
                            else if (it.FormType.Equals(FormType.Email))
                            {
                                @Html.DisplayFor(m => it.NameForm)
                            }
                            else if (it.FormType.Equals(FormType.Phone) || it.FormType.Equals(FormType.TextBoxInt))
                            {
                                @Html.DisplayFor(m => it.IntData)
                            }
                            else if (it.FormType.Equals(FormType.CheckBox))
                            {
                                @Html.DisplayFor(m => it.CheckBoxData)
                            }
                        }
                    </div>
                </div>
            }

            <hr />
        }

    </div>

</div>

<br />
Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount

<pager class="pager-container" list="@Model" options="@PagedListRenderOptions.TwitterBootstrapPager" asp-action="Results" asp-controller="Ancket" />
@section Scripts {
    <link href="~/css/ancket-edit/ancket-edit.css" rel="stylesheet" type="text/css" />
}